### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by StefanoD** [jeffparsons/planetkit#2]
It is better to add a licence to your project.

**Comment by jeffparsons** [comment]
I've been putting this off, because I haven't settled on what's the most appropriate license for the project.

What I _want_ is basically LGPL v3, but with an exception for static linking, so that people could use it in their proprietary Rust projects without having to release their source code. My understanding is that the [MPL 2.0](https://www.mozilla.org/en-US/MPL/) is basically what I've described, so I'm leaning towards that.

My main concern is that anything other than an ultra-permissive license might scare off potential contributors, but I'd ideally like to require people to share their changes if they're not just using planetkit as a library.

Any thoughts on this? Maybe I should just go with MIT (Expat) license to keep things simple, and just accept that some people may choose to not share their changes.

**Comment by jeffparsons** [comment]
Follow-up thought: when I build a game on top of this, I could always release _that_ under the GPL, and keep all the core bits MIT. Maybe that would be a decent compromise.

**Comment by StefanoD** [comment]
I like Apache 2 licence. It's pretty liberal, but everybody who use your code, cannot sue you because of patents, respectively, if they sue you, they are not allowed to use your code anymore.

**Comment by jeffparsons** [comment]
This seems like a decent idea:

https://github.com/Freyskeyd/nlp/issues/10

**Comment by jeffparsons** [comment]
@StefanoD I believe https://github.com/jeffparsons/planetkit/commit/4fc85e11ea370ada51830ab89f23da3b5bea6bd9 resolves this issue.
